on:
  push:
    branches:
    - main
    - release/*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v2  
      with:  
          fetch-depth: 0

    - name: Output
      run: |
        git config --global user.email "bargmaxi@gmail.com"
        git config --global user.name "Maximilian Barg"
          
    - name: Version  
      id: version  
      uses: maximilianbarg/tag-version@master  
      with:  
          production-branch: main

    - name: Output
      run: |
        echo revision ${{steps.version.outputs.revision}}
