on:
  pull_request:
    branches:
    - main

jobs: 
  tag:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout  
      uses: actions/checkout@v2  
      with:  
          ref: ${{ github.ref_name }}   # aktueller Branchname
          fetch-depth: 0                # wichtig für vollständige Tags und History
          token: ${{ secrets.TOKEN }}  # Standard-Token reicht zum Pushen

    - name: Output
      run: |
        git config --global user.email "downisaurier@gmail.com"
        git config --global user.name "Tag Version Bot"
          
    - name: Version  
      id: version  
      uses: maximilianbarg/tag-version@master  
      with:  
          production-branch: main
          test-branch: main  
          dev-branch: dev 

    - name: Output
      run: |
        echo revision ${{steps.version.outputs.revision}}
