on:
  push:
    branches:
    - main
    paths-ignore:
    - 'CHANGELOG.md'
    
jobs: 
  tag:
    runs-on: ubuntu-latest
    steps:   
    - name: Clone repository
      uses: actions/checkout@v4
      with:  
          ref: ${{ github.ref_name }}   # aktueller Branchname
          fetch-depth: 0                # wichtig für vollständige Tags und History
          token: ${{ secrets.TOKEN }}  # Standard-Token reicht zum Pushen
    
    - uses: wemogy/get-release-version-action@v4.3.2
      id: get-release-version
      with:
        prefix: "v"
        suffix: "NONE"
        reference-version-suffix: "NONE"
        bumping-suffix: "hotfix"
        only-bump-suffix: "false"
        create-tag: "true"
        git-username: "Git Tag Version Bot"
        git-email: "downisaurier@gmail.com"
        mode: "semantic"
    
    - run: |
        echo version: ${{ steps.get-release-version.outputs.version }}
        echo version name: ${{ steps.get-release-version.outputs.version-name }}
        echo previous version: ${{ steps.get-release-version.outputs.previous-version }}
        echo previous version name: ${{ steps.get-release-version.outputs.previous-version-name }}
        echo tag created: ${{ steps.get-release-version.outputs.tag-created }}
