on:
  push:
    branches:
    - main
    - release/*

jobs:
  tag: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v2  
      with:  
          fetch-depth: 0

    - name: Output
      run: |
        git config --global user.email "bargmaxi@gmail.com"
        git config --global user.name "Maximilian Barg"
          
    - name: Version  
      id: version  
      uses: maximilianbarg/tag-version@master  
      with:  
          production-branch: main  
          test-branch: main  
          dev-branch: main 

    - name: Output
      run: |
        echo prod-version ${{steps.version.outputs.prod-branch}} 
        echo test-version ${{steps.version.outputs.test-branch}} 
        echo dev-version ${{steps.version.outputs.dev-branch}}
        echo revision ${{steps.version.outputs.revision}}
